version: 2

sources:
  - name: core
    database: new-york-taxi-njoune
    schema: zoomcamp_dataset

    tables:
      - name: synthetic_beverage_sales_data

models:
  - name: fact_sales
    description: ""
    columns:
      - name: sale_id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: order_id
        data_type: string
        description: ""

      - name: customer_id
        data_type: string
        description: ""

      - name: customer_type
        data_type: string
        description: ""

      - name: product
        data_type: string
        description: ""

      - name: category
        data_type: string
        description: ""

      - name: unit_price
        data_type: numeric
        description: ""

      - name: quantity
        data_type: numeric
        description: ""

      - name: discount
        data_type: numeric
        description: ""

      - name: total_price
        data_type: numeric
        description: ""

      - name: region
        data_type: string
        description: ""

      - name: order_date
        data_type: date
        description: ""

  - name: dim_dates
    description: "Date dimension extracted from fact_sales"
    columns:
      - name: Date_ID
        description: "Surrogate key for dates"
        tests:
          - unique
          - not_null

      - name: Order_Date
        description: "The actual order date"

      - name: Year
        description: "Year extracted from Order_Date"

      - name: Quarter
        description: "Quarter extracted from Order_Date"

      - name: Month
        description: "Month extracted from Order_Date"

      - name: Weekday
        description: "ISO weekday number (1 = Monday, 7 = Sunday)"
